-- Generated by Oracle SQL Developer Data Modeler 21.4.2.059.0838
--   at:        2022-05-30 05:19:59 CEST
--   site:      Oracle Database 21c
--   type:      Oracle Database 21c


DROP SYNONYM autorstwa;
DROP SYNONYM konkretna_ocena_wniosku;
DROP SYNONYM ocena_wniosku;
DROP SYNONYM osoby;
DROP SYNONYM recenzje;
DROP SYNONYM wnioski;
commit;


GRANT SELECT, UPDATE, DELETE, INSERT ON OCENA_WNIOSKU TO bd2c040_app WITH GRANT OPTION;
commit;

-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

CREATE OR REPLACE SYNONYM autorstwa FOR bd2c040.autorstwa;

CREATE OR REPLACE SYNONYM konkretna_ocena_wniosku FOR bd2c040.konkretna_ocena_wniosku;

CREATE OR REPLACE SYNONYM ocena_wniosku FOR bd2c040.ocena_wniosku;

CREATE OR REPLACE SYNONYM osoby FOR bd2c040.osoby;

CREATE OR REPLACE SYNONYM recenzje FOR bd2c040.recenzje;

CREATE OR REPLACE SYNONYM wnioski FOR bd2c040.wnioski;

commit;

-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                             0
-- CREATE INDEX                             0
-- ALTER TABLE                              0
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           6
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
