set echo on
set linesize 300
set pagesize 500
spool BD2C040_TEST.LIS

SELECT Tytul, ROUND(OCENA, 2) as srednia_ocen
FROM OCENA_WNIOSKU
ORDER BY ROUND(OCENA, 2);

SELECT TYTUL, ROUND(OCENA, 2) AS najlepszy_wynik
FROM OCENA_WNIOSKU
ORDER BY ROUND(OCENA, 2) DESC
FETCH FIRST 3 ROWS ONLY;

SELECT ID_OSOBY, IMIE, NAZWISKO, count(*) as ile_zlozonych_wnioskow
FROM OSOBY o JOIN AUTORSTWA a ON (o.ID_OSOBY = a.ID_AUTORA)
GROUP BY ID_OSOBY, IMIE, NAZWISKO
ORDER BY count(*) DESC;

SELECT ID_OSOBY, IMIE, NAZWISKO, count(*) as ile_recenzji
FROM OSOBY o JOIN recenzje r ON ( o.ID_OSOBY = r.ID_RECENZENTA )
GROUP BY ID_OSOBY, IMIE, NAZWISKO
ORDER BY count(*) DESC;

SELECT IMIE, NAZWISKO, DATA_URODZENIA, PESEL
FROM OSOBY
WHERE CZY_AUTOR = '1';

SELECT IMIE, NAZWISKO, DATA_URODZENIA, PESEL
FROM OSOBY
WHERE CZY_RECENZENT = '1';

spool off